version: '3.8'

networks:
  app_net:
    driver: bridge
    
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app_net
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
    networks:
        - app_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    user: "0"
    pid: "host"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
        - app_net
    volumes:
      - ./data/grafana:/var/lib/grafana