{
 "title": "Search Engine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap Allocated Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_heap_total_allocated_bytes_total"
    }
   ]
  },
  {
   "title": "CPU Time Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_process_cpu_time_seconds_total"
    }
   ]
  },
  {
   "title": "Search Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "search_counter_count_total" }
   ]
  },
  {
   "title": "Created Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "document_created_count_total" }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "document_deleted_count_total" }
   ]
  }
 ]
}